### 목록
* 준비
    * [사용할 라이브러리 불러오기](#lib)
    * [엘라스틱서치 환경 설정하기](#es_setting)
    * [엘라스틱서치에서 데이터 조회하기](#es_load)
    * [조회한 데이터를 테이블 형태로 만들기](#df)
* Parent Pipeline Aggregation
    * [Derivative Aggregation](#der)
    * [Cumulative Sum Aggregation](#cusum)
    * [Moving Avg Aggregation](#mvavg)
    * [Serial Diff Aggregation](#sd)
---

### 준비

<a name='lib'></a>
#### 사용할 라이브러리 불러오기

In [1]:
import pandas as pd
from elasticsearch import Elasticsearch
import datetime

<a name='es_setting'></a>
#### 엘라스틱서치 환경 설정하기

In [2]:
# 적당한 값을 넣지 않으면 오류가 납니다
es = Elasticsearch()
es_index = 'test_index'
es_type = 'test_type'

<a name='es_load'></a>
#### 엘라스틱서치에서 데이터 조회하기

In [3]:
x = es.search(
      index='test_index', 
      doc_type='test_type', 
      body={
        'query' : {
            'match_all' : {}
        },
        'size' : 50
      }
)

<a name='df'></a>
#### 조회한 데이터를 테이블 형태로 만들기

In [4]:
df = pd.DataFrame([x['hits']['hits'][idx]['_source'] for idx, _ in enumerate(x['hits']['hits'])])
df

,결제카드,고객ip,고객나이,고객성별,고객주소_시도,구매사이트,물건좌표,배송메모,상품가격,상품개수,상품분류,수령시간,예약여부,접수번호,주문시간,판매자평점
0,국민,87.186.104.168,28,여성,광주광역시,옥션,"36.69404479407181, 128.77849366125415",부재중,8000,7,티셔츠,2017-11-04T18:14:01,일반,7,2017-11-01T05:45:01,1
1,하나,61.25.11.51,32,남성,제주특별자치도,티몬,"37.33710638991395, 128.19801428893294",부재중,13000,1,자켓,2017-11-11T03:32:07,일반,8,2017-11-09T16:58:07,3
2,국민,229.171.146.50,35,여성,부산광역시,위메프,"35.20703842551487, 129.88814822339899",주소 오류,22000,1,자켓,2017-11-07T06:46:26,일반,11,2017-11-06T20:03:26,1
3,국민,100.11.208.255,38,여성,충청남도,GS샵,"36.383338520582114, 129.92114062561183",부재중,21000,7,니트,2017-11-05T22:54:35,일반,31,2017-11-03T18:29:35,3
4,롯데,62.73.159.47,28,여성,부산광역시,쿠팡,"37.82022943242058, 127.73799530036115",부재중,21000,1,블라우스,2017-11-10T16:02:36,일반,34,2017-11-09T22:37:36,4
5,신한,28.170.18.252,30,남성,전라북도,티몬,"37.92452138343442, 128.67772065089744",관리실에 맡김,13000,7,티셔츠,2017-11-08T11:11:55,예약,37,2017-11-05T00:41:55,3
6,신한,197.247.246.203,41,여성,충청남도,옥션,"36.663065088906095, 127.92452258110524",환불 요청,15000,7,원피스,2017-11-09T04:28:44,일반,39,2017-11-06T00:27:44,1
7,국민,191.96.106.19,38,여성,인천광역시,쿠팡,"35.42099073543264, 126.40755694075982",환불 요청,12000,1,가디건,2017-11-11T15:26:16,일반,47,2017-11-09T00:40:16,3
8,우리,212.72.222.135,39,여성,전라북도,11번가,"36.204083843135464, 129.24012691531485",부재중,10000,7,셔츠,2017-11-09T08:59:26,일반,48,2017-11-06T10:28:26,5
9,국민,62.36.170.71,39,여성,대구광역시,GS샵,"35.56868760610102, 128.3793660808611",환불 요청,17000,1,스커트,2017-11-11T15:36:16,일반,1,2017-11-08T02:00:16,3
10,국민,133.45.118.127,33,남성,대전광역시,GS샵,"37.87201865369285, 126.75507159240954",주소 오류,6000,1,티셔츠,2017-11-09T21:12:40,일반,3,2017-11-07T15:29:40,1
11,국민,47.181.162.243,25,남성,경상남도,g마켓,"35.34373921692427, 129.82903178684617",상품 이상,5000,7,점퍼,2017-11-13T02:55:41,일반,12,2017-11-09T17:35:41,3
12,우리,128.195.15.116,33,여성,경상북도,11번가,"36.75103099470225, 127.86900765081127",상품 이상,17000,7,셔츠,2017-11-15T07:17:17,일반,17,2017-11-10T15:53:17,5
13,우리,50.130.83.231,27,남성,경기도,위메프,"37.78723366594554, 127.99751085613701",상품 이상,17000,7,팬츠,2017-11-05T09:26:18,일반,20,2017-11-02T05:28:18,1
14,국민,161.124.192.177,44,여성,서울특별시,옥션,"37.89167509773231, 129.89861013896265",상품 이상,21000,1,니트,2017-11-04T18:14:51,일반,26,2017-11-04T08:22:51,5
15,신한,110.126.36.108,20,남성,부산광역시,티몬,"35.73286207547757, 128.237959511983",주소 오류,28000,1,팬츠,2017-11-06T13:32:22,일반,28,2017-11-03T20:15:22,4
16,우리,166.50.85.215,43,남성,대전광역시,11번가,"36.43460626090956, 127.63620328140061",주소 오류,14000,1,팬츠,2017-11-10T03:34:34,일반,38,2017-11-06T06:26:34,3
17,롯데,158.166.47.177,27,여성,대구광역시,GS샵,"35.917645691146234, 128.57392985531072",시간 내에 배송 못함,8000,7,원피스,2017-11-11T10:43:49,일반,42,2017-11-10T17:03:49,1
18,우리,15.236.59.18,35,여성,전라남도,옥션,"37.509031233865585, 127.79764126292338",상품 이상,23000,1,청바지,2017-11-07T20:21:07,일반,43,2017-11-05T04:57:07,4
19,신한,1.40.46.8,30,여성,경상남도,쿠팡,"36.808561479311756, 128.05531367120452",환불 요청,25000,7,원피스,2017-11-08T02:13:44,일반,44,2017-11-04T14:45:44,4
20,국민,225.158.131.104,28,남성,경상북도,GS샵,"37.74860963773523, 129.80505939646017",부재중,21000,7,베스트,2017-11-07T02:24:17,일반,46,2017-11-06T12:47:17,1
21,우리,192.10.251.35,26,남성,대구광역시,GS샵,"37.784031270602306, 127.89322344305637",상품 이상,11000,7,남방,2017-11-12T11:16:23,일반,49,2017-11-08T01:14:23,4
22,국민,153.183.125.58,29,여성,강원도,11번가,"36.02446595440512, 128.37338819474155",상품 이상,17000,7,블라우스,2017-11-05T21:01:56,일반,2,2017-11-03T10:37:56,3
23,하나,148.19.203.84,33,남성,강원도,옥션,"35.1888202093495, 128.58916079461932",상품 이상,19000,1,코트,2017-11-10T22:46:55,일반,5,2017-11-06T04:46:55,2
24,롯데,165.17.49.145,42,여성,전라북도,g마켓,"35.418743037985074, 126.58583972979557",주소 오류,10000,7,블라우스,2017-11-04T18:20:20,일반,14,2017-11-02T04:33:20,4
25,국민,40.125.200.155,22,여성,경상남도,11번가,"35.355523370930555, 126.64192463067211",관리실에 맡김,18000,7,팬츠,2017-11-05T08:18:15,일반,15,2017-11-05T00:20:15,3
26,삼성,148.212.8.17,34,여성,인천광역시,g마켓,"35.42959783489421, 127.86878397078254",시간 내에 배송 못함,5000,7,스커트,2017-11-07T06:14:42,일반,16,2017-11-07T02:40:42,1
27,하나,218.249.128.251,29,남성,대전광역시,11번가,"35.96903290104712, 129.07378470988706",부재중,26000,1,베스트,2017-11-09T09:33:52,일반,24,2017-11-05T04:18:52,1
28,국민,72.142.47.220,45,여성,경상남도,GS샵,"36.234355607886094, 127.70245073328189",상품 이상,17000,1,스커트,2017-11-12T00:00:00,일반,29,2017-11-09T21:57:00,1
29,신한,206.168.117.214,35,여성,서울특별시,g마켓,"37.85255506645674, 129.5384026998396",상품 이상,9000,7,팬츠,2017-11-05T14:28:24,일반,30,2017-11-04T08:22:24,1
30,우리,105.222.155.59,38,여성,경상북도,11번가,"35.85935017775508, 128.89657781645107",상품 이상,9000,1,티셔츠,2017-11-07T11:15:11,일반,40,2017-11-07T01:32:11,1
31,우리,193.198.70.84,38,남성,대전광역시,g마켓,"35.30219693882553, 127.14648221893185",상품 이상,7000,1,수트,2017-11-13T05:18:29,일반,50,2017-11-09T03:28:29,3
32,롯데,230.250.155.4,41,여성,충청북도,옥션,"35.29706664216842, 128.3612301978423",시간 내에 배송 못함,27000,7,코트,2017-11-13T23:19:29,일반,6,2017-11-10T23:15:29,1
33,신한,246.158.150.193,19,남성,충청북도,티몬,"35.779125040380016, 127.75099764954581",부재중,23000,1,점퍼,2017-11-05T00:16:58,일반,9,2017-11-04T20:38:58,1
34,하나,96.7.37.144,43,남성,광주광역시,g마켓,"37.40789435127714, 126.05827428381714",상품 이상,10000,7,셔츠,2017-11-07T00:43:09,일반,10,2017-11-02T19:50:09,4
35,우리,205.28.195.79,34,남성,경상북도,티몬,"36.077851040805484, 128.75372618836693",주소 오류,5000,1,팬츠,2017-11-12T08:40:08,일반,13,2017-11-09T17:10:08,4
36,하나,114.136.56.2,17,여성,서울특별시,11번가,"36.48704797751413, 126.6969369579494",상품 이상,27000,1,코트,2017-11-04T01:56:01,일반,22,2017-11-01T13:52:01,5
37,시티,229.140.131.222,41,남성,전라남도,위메프,"35.95241916226646, 126.19617819934207",시간 내에 배송 못함,19000,7,남방,2017-11-14T23:32:55,일반,33,2017-11-10T15:39:55,3
38,우리,99.91.170.16,27,남성,울산광역시,옥션,"37.77159638148331, 129.01728642206382",상품 이상,20000,7,자켓,2017-11-10T13:47:53,예약,35,2017-11-09T14:50:53,4
39,국민,20.123.245.214,18,남성,부산광역시,옥션,"35.5442002376651, 129.41859537141949",부재중,26000,1,가디건,2017-11-10T18:20:28,일반,36,2017-11-08T10:27:28,5
40,신한,47.144.234.168,22,남성,경상남도,GS샵,"35.065572757040094, 129.03874692593698",부재중,22000,7,수트,2017-11-04T17:49:56,일반,4,2017-11-03T20:24:56,3
41,롯데,183.105.66.209,29,여성,부산광역시,g마켓,"36.329515956982675, 129.3451408956394",상품 이상,12000,1,팬츠,2017-11-08T00:50:27,예약,18,2017-11-04T05:32:27,5
42,우리,27.147.153.211,26,남성,경상북도,옥션,"36.529942877901696, 127.35651155748744",부재중,23000,7,팬츠,2017-11-05T05:03:26,일반,19,2017-11-02T13:19:26,2
43,롯데,123.98.207.116,31,여성,충청북도,11번가,"35.026188551993776, 126.46516312933772",환불 요청,18000,1,스커트,2017-11-04T18:12:07,일반,21,2017-11-04T02:16:07,1
44,하나,158.178.232.9,45,여성,전라남도,위메프,"35.482103793610165, 126.2470485740534",부재중,22000,7,팬츠,2017-11-14T05:05:55,일반,23,2017-11-10T16:14:55,5
45,하나,52.171.239.14,24,여성,서울특별시,g마켓,"37.26359959190257, 126.74869569415385",상품 이상,13000,7,티셔츠,2017-11-08T10:50:38,일반,25,2017-11-07T18:24:38,5
46,우리,89.210.213.227,36,여성,울산광역시,g마켓,"36.5349517039517, 127.49478668041986",시간 내에 배송 못함,12000,1,스커트,2017-11-06T00:10:21,일반,27,2017-11-04T11:48:21,1
47,신한,164.141.204.177,17,남성,부산광역시,GS샵,"37.59737780622949, 126.7120648155864",부재중,11000,7,베스트,2017-11-03T11:55:38,일반,32,2017-11-03T01:42:38,2
48,우리,152.136.3.129,34,여성,경상남도,티몬,"36.78817753074974, 128.159280759304",관리실에 맡김,9000,7,블라우스,2017-11-08T10:19:21,일반,41,2017-11-07T03:44:21,3
49,우리,55.165.131.9,19,여성,대구광역시,11번가,"35.01506669708026, 127.47582075972228",주소 오류,27000,1,니트,2017-11-08T22:17:55,일반,45,2017-11-08T03:43:55,1

### Parent Piepline Aggregation

In [6]:
df.index = pd.to_datetime(df['주문시간'])
df_daily_count = df.resample('D').count().iloc[:, 0]
df_daily_count

주문시간
2017-11-01    2
2017-11-02    4
2017-11-03    5
2017-11-04    7
2017-11-05    4
2017-11-06    6
2017-11-07    5
2017-11-08    4
2017-11-09    8
2017-11-10    5
Freq: D, Name: 결제카드, dtype: int64

<a name="der"></a>
#### Derivative Aggregation 

: (Date) Histogram에서 연속된 두 bucket의 aggregated된 값의 차이를 구한다. (현재 값 - 이전 값)

In [7]:
df_daily_count_diff = df_daily_count.diff()
df_derivative = pd.concat([df_daily_count, df_daily_count_diff], axis=1)
df_derivative.columns.values[0], df_derivative.columns.values[1]  = '일별 판매 개수', '전일 대비 판매 개수 변화'
df_derivative

            일별 판매 개수  전일 대비 판매 개수 변화
주문시간
2017-11-01         2             NaN
2017-11-02         4             2.0
2017-11-03         5             1.0
2017-11-04         7             2.0
2017-11-05         4            -3.0
2017-11-06         6             2.0
2017-11-07         5            -1.0
2017-11-08         4            -1.0
2017-11-09         8             4.0
2017-11-10         5            -3.0

<a name="cusum"></a>

#### Cumulative Sum Aggregation
: (Date) Histogram에서 bucket의 aggregate된 값의 누적합 반환한다

In [8]:
df_daily_count_cumsum = df_daily_count.cumsum()
df_cumsum = pd.concat([df_daily_count, df_daily_count_cumsum], axis=1)
df_cumsum.columns.values[0], df_cumsum.columns.values[1]  = '일별 판매 개수', '누적 판매 개수'
df_cumsum

            일별 판매 개수  누적 판매 개수
주문시간
2017-11-01         2         2
2017-11-02         4         6
2017-11-03         5        11
2017-11-04         7        18
2017-11-05         4        22
2017-11-06         6        28
2017-11-07         5        33
2017-11-08         4        37
2017-11-09         8        45
2017-11-10         5        50

<a name="mvavg"></a>
#### Moving Avg Aggregation

: (Date) Histogram에서 bucket의 aggregate된 값들의 이동평균 반환한다

In [9]:
df_daily_count_rolling = df_daily_count.rolling(window=2).mean()
df_rolling = pd.concat([df_daily_count, df_daily_count_rolling], axis=1)
df_rolling.columns.values[0], df_rolling.columns.values[1]  = '일별 판매 개수', '이틀 간 판매 개수의 이동 평균'
df_rolling

            일별 판매 개수  이틀 간 판매 개수의 이동 평균
주문시간
2017-11-01         2                NaN
2017-11-02         4                3.0
2017-11-03         5                4.5
2017-11-04         7                6.0
2017-11-05         4                5.5
2017-11-06         6                5.0
2017-11-07         5                5.5
2017-11-08         4                4.5
2017-11-09         8                6.0
2017-11-10         5                6.5

<a name="sd"></a>
#### Serial Diff Aggregation 

: (Date) Histogram에서 현재 bucket의 aggregate된 값과 이전 {n}번째 bucket의 aggregate된 값의 차이를 반환한다 (현재 - 이전)

In [10]:
df_daily_count_diff_ = df_daily_count.diff(periods=2)
df_derivative_ = pd.concat([df_daily_count, df_daily_count_diff_], axis=1)
df_derivative_.columns.values[0], df_derivative_.columns.values[1]  = '일별 판매 개수', '전전일 대비 판매 개수 변화'
df_derivative_

            일별 판매 개수  전전일 대비 판매 개수 변화
주문시간
2017-11-01         2              NaN
2017-11-02         4              NaN
2017-11-03         5              3.0
2017-11-04         7              3.0
2017-11-05         4             -1.0
2017-11-06         6             -1.0
2017-11-07         5              1.0
2017-11-08         4             -2.0
2017-11-09         8              3.0
2017-11-10         5              1.0